[0m03:35:13.413290 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1075ae490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109646f10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109646be0>]}


============================== 03:35:13.416160 | 7a960629-cc0b-4f3c-abe2-432a09dc8e4b ==============================
[0m03:35:13.416160 [info ] [MainThread]: Running with dbt=1.9.2
[0m03:35:13.416509 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/daniellira/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m03:35:50.996610 [debug] [MainThread]: Starter project path: /Users/daniellira/Dev/desafio-pipeline-brt/venv/lib/python3.9/site-packages/dbt/include/starter_project
[0m03:35:51.007193 [info ] [MainThread]: 
Your new dbt project "brt_data_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m03:35:51.007769 [info ] [MainThread]: Setting up your profile.
[0m03:35:51.015240 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m03:35:51.020325 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 37.656136, "process_in_blocks": "0", "process_kernel_time": 0.167088, "process_mem_max_rss": "90144768", "process_out_blocks": "0", "process_user_time": 0.712181}
[0m03:35:51.020905 [debug] [MainThread]: Command `dbt init` failed at 03:35:51.020816 after 37.66 seconds
[0m03:35:51.022185 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1075ae490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1096e8fa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1096c7d00>]}
[0m03:35:51.022926 [debug] [MainThread]: Flushing usage events
[0m03:35:51.719088 [debug] [MainThread]: An error was encountered while trying to flush usage events
